---
- name: COPY RUN START CONFIG
  hosts: ACSR1kv
  become: true
  gather_facts: false
  connection: local

  tasks:
    - name: SAVE CONFIGS
      ios_config:
        lines:
          - "do write memory"
    - name: SAVE OUTPUT TO ./ios_configurations/
      ios_command:
        commands:
          - show running-config
      register: config
    - name: Save to File
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "ios_configurations/copy_run_{{ inventory_hostname }}.txt"
